#include "tests.h"
DEFINE_TEST_CASE(rc_does_count);
DEFINE_TEST_CASE(rc_reassign);
DEFINE_TEST_CASE(fs_basic_udev);
DEFINE_TEST_CASE(list_push_pop_back);
DEFINE_TEST_CASE(list_push_pop_front);
DEFINE_TEST_CASE(list_at);
DEFINE_TEST_CASE(kernel_heap_kmalloc_single);
DEFINE_TEST_CASE(kernel_heap_kmalloc_multi_ordered);
DEFINE_TEST_CASE(kernel_heap_merge_free);
DEFINE_TEST_CASE(string_strlen);
DEFINE_TEST_CASE(string_strcmp);
DEFINE_TEST_CASE(string_eq);
DEFINE_TEST_CASE(string_concat);
DEFINE_TEST_CASE(string_slice);
DEFINE_TEST_CASE(string_split);
DEFINE_TEST_CASE(hashmap_int_adds_keys);
DEFINE_TEST_CASE(hashmap_int_get);
DEFINE_TEST_CASE(hashmap_int_collision);
